---
- name: Install ntp on master
  tags: ntp
  yum: pkg={{ item }} state=latest
  when: is_master is defined
  with_items:
     - ntp

- name: enable ntpd service
  tags: ntp
  when: is_master is defined
  service: name=ntpd state=started enabled=yes

- name: Install ntpdate on clients
  tags: ntp
  yum: pkg={{ item }} state=latest
  when: is_client is defined
  with_items:
     - ntpdate

- name: Update time from master once
  tags: ntp
  when: not is_master is defined
  command: ntpdate {{ groups['master'][0] }}

- name: Set timezone
  tags: ntp
  command: timedatectl set-timezone {{ time_zone }}
