# This playbook setup nfs (http://nfs.sourceforge.net/) capability.
#
# Copyright (c) 2013-2014 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- name: install nfs package
  tags: nfs
  yum: pkg={{ item }}
       state=present 
  with_items:
    - nfs-utils

- name: start nfs-server
  tags: nfs
  service: name=nfs state=started enabled=yes
  
- name: add an export
  tags: nfs
  lineinfile: dest=/etc/exports
              regexp=''
              insertafter=EOF
              line="{{ nfs_share_dir }} *(rw,nohide,insecure,no_subtree_check,sync)"

- name: restart nfs-server
  tags: nfs
  service: name=nfs state=restarted
