---
- name: create bare-metal directory
  tags:
    - env
  file: path=/home/cluser/bare-metal/
        mode=0755
        owner=cluser
        state=directory

- name: create bare-metal mfiles
  tags:
    - env
  file: path=/home/cluser/bare-metal/{{ item }}
        mode=0755
        owner=cluser
        state=touch
  with_items:
    - mfile_all
    - mfile_slaves

- name: "Build cluster mfile"
  tags:
    - env
  lineinfile: dest=/home/cluser/bare-metal/mfile_all regexp='.*{{ item }}$' line="{{item}}" state=present
  with_items: groups['all']

- name: "Build slaves mfile"
  tags:
    - env
  lineinfile: dest=/home/cluser/bare-metal/mfile_slaves regexp='.*{{ item }}$' line="{{item}}" state=present
  with_items: groups['slaves']
