---
- name: check if register is already running
  shell: docker ps
  register: docker_ps
  tags:
    - docker
    - container

- name: start registry container
  tags:
    - docker
    - container
  script: /usr/local/bin/start_container.sh registry
  when: docker_ps.stdout.find(' registry:') == -1

- name: start monster container
  tags:
    - docker
    - container
  command: /usr/local/bin/start_container.sh monster
  when: docker_ps.stdout.find(' qnib/monster:') == -1
#  docker: 
#    image=registry env="STORAGE_PATH=/registry" 
#    volumes="/var/lib/docker-registry:/registry" 
#    name=registry state=running 
#    docker_url=tcp://localhost:6000
