---
# This task is used to mount a filesystem via NFS.
# 
# Variables you need to define:
# nfsserver:   the nfs server to mount from
# nfspath:     the remote filesystem to mount from the nfs server
# nfsmount:    the directory where you want to mount the filesystem.
# nfsoptions:  options to use when mounting the filesystem. If not
#              defined, `rw,sync` will be used.
#
# Please note that the task will check if the ${nfsmount} directory
# exists and create it otherwise.
#

- name: install nfs client
  action: yum pkg=nfs-utils state=present
  tags: 
    - nfs

- name: Ensure rpcbind is running (CentOS)
  action: service name=rpcbind state=started enabled=yes
  tags: 
    - nfs

- name: Ensure {{ nfsmount }} directory exists
  action: file path={{ nfsmount }} state=directory
  tags: 
    - nfs

- name: configure /etc/fstab on clients
  action: mount name={{ nfsmount }} src={{ nfsserver }}:{{ nfspath }} fstype=nfs4 opts="_netdev,auto" state=mounted
  tags:
    - nfs
