---
- name: create input_files directory
  tags: hpcg
  file: path=/opt/hpcg/{{ item }} mode=0755 state=directory
  with_items:
#  - input_files
  - job_scripts

#- name: create job scripts
#  tags: hpcg
#  include: create_job_scripts.yml
#  when: is_nfs_server is defined

- name: copy helper scripts
  tags: hpcg
  copy: src=usr/local/bin/{{ item }} dest=/usr/local/bin/{{ item }} owner=root group=root mode=0755
  with_items:
  - eval_hpcg.py

