---
- name: add repositories
  tags: base
  copy: src=./{{ dir_pre | default }}/etc/yum.repos.d/{{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo owner=root group=root mode=0644
  with_items:
  - epel
  - qnib

- name: stop firewalld
  tags: base
  service: name=firewalld state=stopped enabled=no

- name: disable selinux within config
  tags: base
  selinux: state=disabled
  
- name: Disable selinux now
  tags:
    - base
  command: setenforce 0
  
- name: Copy supervisord systemd service
  tags: base
  copy: src=usr/lib/systemd/system/supervisord.service dest=/usr/lib/systemd/system/supervisord.service owner=root group=root mode=0644

- name: start supervisord
  tags: base
  service: name=supervisord state=started enabled=yes


