---
- name: add repositories
  tags: base
  copy: src=./{{ dir_pre | default }}/etc/yum.repos.d/{{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo owner=root group=root mode=0644
  when: not is_container is defined
  with_items:
  - epel
  - qnib

- name: stop firewalld
  tags: base
  when: not is_container is defined
  service: name=firewalld state=stopped enabled=no

- name: disable selinux
  tags: base
  when: not is_container is defined
  selinux: state=disabled

