---
- include: base_setup.yml
  when: not is_container is defined
- include: basic_pkg.yml
  when: not is_container is defined
- include: setup_supervisord.yml
  when: not is_container is defined
- include: bootstrap_container.yml
  when: is_container is defined
