---
- name: install docker-spotter
  yum: pkg={{ item }} state=present
  tags: 
  - docker
  - spotter
  with_items:
  - openvswitch 
  - docker-spotter

- name: ensure openvswitch and docker-spotter are running
  service: name={{ item }} state=started
  tags:
     - docker
  with_items:
  - openvswitch 
  - docker-spotter

