---
- name: fetch all running container list
  shell: docker ps
  register: docker_ps
  tags:
    - docker
    - container

- name: start registry container
  tags:
    - docker
    - container
  when: run_registry is defined and in docker_ps.stdout.find(' registry:') == -1
  shell: /usr/local/bin/start_container.sh registry

- name: start monster container
  tags:
    - docker
    - container
  shell: /usr/local/bin/start_container.sh monster
  when: run_monster is defined and in docker_ps.stdout.find(' qnib/monster:') == -1

- name: start centos7 compute container
  tags:
    - docker
    - container
    - compute
  shell: /usr/local/bin/start_container.sh centos7_thin_compute
  when: docker_ps.stdout.find(' qnib/centos7_thin_compute:') == -1

